#!/bin/sh
PATH=/bin:/usr/bin:/sbin:/usr/sbin

# === Bootstrap ===

scr_print "Bootstrapping..."

# looking for the proper XIVO version
pkg_manager update
pkg_manager -y install xivo-fai-dev

pkg_manager update

# packages containing source lists could be upgradable
pkg_manager -y dist-upgrade
pkg_manager update

VERSION=$(apt-cache show --no-all-versions pf-xivo | grep Version | cut -d\  -f2)
if [ -z "${VERSION}" ]; then
	scr_println "XIVO not found"
	exit_error
fi

echo ${VERSION} >$POSTINSTDIR/xivo_initial_version
echo startup=no > /etc/default/xivo

scr_progress_done


# === Install ===

scr_print "XIVO ${VERSION} installation in progress"

# inetd not needed
if [ -e /etc/init.d/inetd ]; then
	invoke-rc.d inetd stop
	update-rc.d -f inetd remove
fi

# XIVO install
# install kmods before using it, to ensure init scripts won't fail miserably
pkg_manager -y install dahdi-linux-modules-${KERN_REL}
scr_progress
export LANG=en_US.UTF-8
pkg_manager -y install pf-xivo
pkg_manager -y install asterisk-moh-opsound-g722 asterisk-moh-opsound-gsm asterisk-moh-opsound-wav
pkg_manager -y install xivo-dev-ssh-pubkeys
scr_progress

scr_progress_done


# === Configuration ===

scr_println "XIVO configuration in progress..."

# initialize databases
xivo-update-db

# Zaptel config
# (ignore errors caused by detection and config generation)
# (btw, the machine may not have any DAHDI interface)
(
	# (restart to autoload modules)
	invoke-rc.d dahdi restart
	dahdi_genconf
	# fix rights
	CONFIG="/etc/asterisk/dahdi-channels.conf"
	if [ -e "${CONFIG}" ]; then
		chown asterisk:www-data ${CONFIG}
		chmod 660 ${CONFIG}
	fi
) >/dev/null 2>/dev/null || true
scr_progress

xivo-service restart all
scr_progress

scr_progress_done

