#!/bin/bash

set +x

export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
export DEBCONF_NOWARNINGS=yes


scr_clear()
{
    clear
}

scr_print()
{
    echo -en $1
}

scr_println()
{
    scr_print "$1\n\r"
}

scr_println_ok()
{
    scr_println "\033[0;32;40m$1\033[0;38;40m"
}

scr_println_error()
{
    scr_println "\033[0;31;40m$1\033[0;38;40m"
}

scr_progress()
{
    scr_print "."
}

scr_progress_done()
{
    scr_println_ok "DONE"
}

scr_begin()
{
    scr_print "\033[0;38;40m"
}

scr_end()
{
    scr_print "\033[0;37;40m"
}

exit_error()
{
    scr_println
    scr_println
    scr_println_error "Installation Failed !!!"
    scr_println
    scr_println "The installation log is available at $postinst_log."
    scr_println

    scr_end
    exit 1
}

display_final_info()
{
    scr_println
    scr_println_ok "Installation successful !!!"

    MSG=$(ip addr show | grep "inet .* scope global")
    scr_println
    scr_println "Network information:"
    scr_println "${MSG}"
}

finish_fai()
{

    rm /etc/apt/apt.conf

    # packages cleanup
    pkg_manager clean

    # remove FAI hook
    # clean rc.local
    sed -i "s:sh /var/lib/xivo-fai/postinst_script_launcher::" /etc/rc.local
}

pkg_manager()
{
    # in this subshell, the trap on ERR is _not_ inherited
    (
        for I in $(seq 1 3); do
            apt-get -o Dpkg::Options::="--force-confold" $*
            if [ $? = 0 ]; then
                exit 0
            fi
        done
        exit 1
    )
    if [ $? != 0 ]; then
        exit_error
    fi
}

has_ip_addr_via_dhcp()
{
    network_interface="$(find /var/run/dhclient.* -printf "%f\n" | sed -r 's/dhclient\.(.*)\.pid/\1/' | head -n 1)"
    if [ -z "$network_interface" ] ; then
        echo "Could not find an interface configured by dhclient"
        return 2
    fi
    if [ -n "$(ip -f inet addr show ${network_interface} | grep 'inet ')" ] ; then
        return 0
    fi
    return 1
}

check_ip_address()
{
    tries_left=10
    while ! has_ip_addr_via_dhcp && [ $tries_left -gt 0 ] ; do
        sleep 3
        tries_left=$(($tries_left - 1))
    done
    if [ $tries_left -eq 0 ] ; then
        return 1  # timeout
    fi
    return 0
}


# catch errors
trap exit_error ERR

scr_begin
scr_clear
scr_println
scr_println "=*=  Wazo Fully Automatic Installation =*="
scr_println

# discovery
SUITE=$(cat $postinst_dir/suite)
CLASSES=$(cat $postinst_dir/classes)
KERN_REL=$(uname -r)
KERN_FLAVOUR=$(echo ${KERN_REL} | cut -d\- -f3)

echo "Checking IP address configuration"
if ! check_ip_address ; then
    echo "Could not get IP address. Please check your DHCP configuration. Exiting ..."
    exit_error
fi
echo "IP address OK"

dnsdomain=$(dnsdomainname)
mirror="mirror.${dnsdomain}:3142"

sed -i -r "s#http://$mirror/debian#http://deb.debian.org/debian/#" /etc/apt/sources.list
echo "Acquire::http { Proxy \"http://$mirror\"; };" > /etc/apt/apt.conf

scr_print "Base installation in progress"

pkg_manager update
scr_progress

# remove unused lv, partman limitation
unused_lv="/dev/data/to_remove"
if [ -L $unused_lv ]; then
    lvremove -f $unused_lv
fi

# install ca-certificate to be able to git clone https://github...
pkg_manager -yq install ca-certificates
scr_progress

# configure ssh
sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl restart ssh

scr_progress_done

# run custom postinst commands if needed
for script in $(find $postinst_dir/postinst.d -mindepth 1 -maxdepth 1 | sort); do
    . $script
done

pkg_manager update
scr_progress

finish_fai
display_final_info

scr_end
