#!/bin/sh

. /usr/share/debconf/confmodule

CLASSES=$(debconf-get auto-install/classes | sed 's/,/ /g')

PROXY=$(debconf-get local/proxy)
if [ -n "${PROXY}" ]; then
	echo "Proxy config override: ${PROXY}" >>/tmp/location_config.log
	db_fset mirror/http/proxy seen false
else
	echo "Detecting location..." >>/tmp/location_config.log
	IFACE=$(ip link show | grep "UP" | grep "eth[0-9]" | cut -d: -f2 | sed 's/ //g')
	echo "Interface: ${IFACE}" >>/tmp/location_config.log
	IP=$(ip addr show ${IFACE} | grep -E "\binet\b .* scope global ${IFACE}\$" | sed -r 's/^ +//' | cut -d\  -f2)
	echo "IP: ${IP}" >>/tmp/location_config.log
	SUBNET=$(echo ${IP} | cut -d. -f 1-2)
	echo "Subnet: ${SUBNET}" >>/tmp/location_config.log
	DNSDOMAIN=$(debconf-get netcfg/get_domain)
	echo "DNS Domain: ${DNSDOMAIN}" >>/tmp/location_config.log

	MIRROR=
	if [ "${DNSDOMAIN}" = "lan-puteaux.avencall.com" ]; then
		MIRROR="mirror.lan-puteaux.avencall.com"
	fi
	if [ "${DNSDOMAIN}" = "lan-limonest.avencall.com" ]; then
		MIRROR="mirror.lan-limonest.avencall.com"
	fi
	if [ "${DNSDOMAIN}" = "atarakt.com" ]; then
		MIRROR="mirror.atarakt.com:3142"
	fi


	if [ -n "${MIRROR}" ]; then
		echo "Local config selected, using mirror: ${MIRROR}" >>/tmp/location_config.log

		# do not ask questions about proxy
		db_fset mirror/protocol seen true
		db_fset mirror/http/proxy seen true

		db_set mirror/country "enter information manually"
		db_set mirror/http/countries "enter information manually"
		db_set mirror/http/hostname "${MIRROR}"
		db_set mirror/http/mirror "${MIRROR}"
		db_set apt-setup/hostname "${MIRROR}"
		# dirty hack because 'apt-setup/security_path' key is not available (at least on Etch)
		db_set apt-setup/security_host "${MIRROR}/debian-security"
		#db_set apt-setup/security_path "/debian-security"
	fi
fi

# discovery
export KERN_REL=$(uname -r)
export KERN_FLAVOUR=$(echo ${KERN_REL} | cut -d\- -f3)
if [ "${KERN_FLAVOUR}" = "486" ]; then
  KERN_FLAVOUR="686"
fi

export CUST_PRESEED=/tmp/custom_preseed
touch ${CUST_PRESEED}

# run classes early_script scripts with a preserved order
if [ -n "${CLASSES}" ]; then
	for CLASS in ${CLASSES}; do
		preseed_fetch /classes/${CLASS}/early_script /tmp/early_script_${CLASS}
		chmod a+x /tmp/early_script_${CLASS}
		export CLASS
		log-output -t early_script_${CLASS} sh /tmp/early_script_${CLASS}
	done
fi

if ! grep -q "base-installer/kernel/image" ${CUST_PRESEED}; then
	# using db_set is not possible for 'select' parameters, only for strings
	echo "d-i base-installer/kernel/image select linux-image-2.6-${KERN_FLAVOUR}" >>${CUST_PRESEED}
fi

debconf-set-selections ${CUST_PRESEED}

#exit 0
