#!/bin/sh

# allow late preseeding via packaging
sed -i -r 's/^DPkg::Pre-Install-Pkgs/\/\/DPkg::Pre-Install-Pkgs/' /etc/apt/apt.conf.d/70debconf

# configure apt
if [ -x /usr/bin/apt-key ]; then
	apt-get -y install gnupg
	wget http://mirror.xivo.fr/ziyi_proformatique_current.asc -O - | apt-key add -
	wget http://mirror.xivo.fr/xivo_current.key -O - | apt-key add -
fi

cat << EOF >> /etc/apt/apt.conf.d/90pf
Aptitude::Recommends-Important "false";
Aptitude::Purge-Unused "true";
APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::Get::AutomaticRemove "true";
EOF

cat << EOF >> /etc/apt/sources.list.d/pf.sources.list
# Proformatique Debian Repository
deb http://mirror.xivo.fr/debian #SUITE# main non-free
#deb-src http://mirror.xivo.fr/debian #SUITE# main non-free
EOF

for FILE in $(find /etc/apt -type f); do
	sed -i "s/#SUITE#/${SUITE}/g" ${FILE}
done

apt-get update

