#!/bin/sh

# === Bootstrap ===

scr_print "Bootstrapping..."

# looking for the proper XIVO version
#echo "deb http://mirror.wazo.community/debian-private/clients/microsoft etch-xivo-gallifrey-dev restricted" >/etc/apt/sources.list.d/pf-xivo-microsoft.sources.list
pkg_manager update
scr_progress

scr_progress_done


# === Install ===

scr_print "Microsoft XIVO addons installation in progress..."

# ensure forked packages are up-to-date
pkg_manager -y dist-upgrade
scr_progress

scr_progress_done

