#!/bin/sh

echo "d-i base-installer/kernel/image select linux-image-2.6-${KERN_FLAVOUR}-etchnhalf" >>${CUST_PRESEED}

# grub fix
preseed_fetch /classes/${CLASS}/grub_fix.sh /tmp/grub_fix.sh
chmod a+x /tmp/grub_fix.sh

# ask this question, so people are able to manually apply the grub fix
# /!\ DOES NOT WORK...
#db_fset grub-installer/only_debian seen false
#db_fset grub-installer/with_other_os seen false
# /!\ DOES NOT WORK EITHER...
#db_reset grub-installer/only_debian
#db_reset grub-installer/with_other_os

