#!/bin/sh

export postinst_dir=/var/lib/xivo-fai

###########################################################################

echo "Bootstrapping FAI..."

com="$postinst_dir/postinst_script"
if [ -f $postinst_dir/debug ]; then
  $com
else
  $com >/dev/null 2>/dev/null
fi
