#!/bin/sh

# allow late preseeding via packaging
sed -i -r 's/^DPkg::Pre-Install-Pkgs/\/\/DPkg::Pre-Install-Pkgs/' /etc/apt/apt.conf.d/70debconf

# configure apt
if [ -x /usr/bin/apt-key ]; then
	apt-get -y install gnupg
	wget http://dak.proformatique.com/ziyi_proformatique_current.asc -O - | apt-key add -
fi
FAI_DATA_PATH=fai.proformatique.com/fai/base/${SUITE}
wget -r -P /tmp/zzz ftp://${FAI_DATA_PATH}
cp -r /tmp/zzz/${FAI_DATA_PATH}/* /etc/apt/
for FILE in $(find /etc/apt -type f); do
	sed -i "s/#SUITE#/${SUITE}/g" ${FILE}
done

apt-get update

