#!/bin/sh
#!/bin/sh
### BEGIN INIT INFO
# Provides:          postinst_script_launcher
# Required-Start:    $local_fs $remote_fs $syslog $named $network $time
# Required-Stop:     $local_fs $remote_fs $syslog $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pf-fai xivo installation script
# Description:      Proformatique xivo postins fai scripts
### END INIT INFO


# Parameters
export POSTINSTDIR=/var/lib/pf-fai
export POSTINST_LOG=/var/log/pf-fai/postinst.log


###########################################################################

echo "Bootstrapping FAI..."

mkdir -p $(dirname ${POSTINST_LOG})
echo "########################################################################" >>${POSTINST_LOG}
date >>${POSTINST_LOG}

COM="script -a -c ${POSTINSTDIR}/postinst_script ${POSTINST_LOG}"
if [ -f ${POSTINSTDIR}/debug ]; then
  ${COM}
else
  ${COM} >/dev/null 2>/dev/null
fi

