#!/bin/sh

. /usr/share/debconf/confmodule


PROXY=$(debconf-get local/proxy)
if [ -n "${PROXY}" ]; then
	echo "Proxy config override: ${PROXY}" >>/tmp/location_config.log
	db_fset mirror/http/proxy seen false
else
	echo "Detecting location..." >>/tmp/location_config.log
	IFACE=$(ip link show | grep "UP" | grep "eth[0-9]" | cut -d: -f2 | sed 's/ //g')
	echo "Interface: ${IFACE}" >>/tmp/location_config.log
	IP=$(ip addr show ${IFACE} | grep -E "\binet\b .* scope global ${IFACE}\$" | sed -r 's/^ +//' | cut -d\  -f2)
	echo "IP: ${IP}" >>/tmp/location_config.log
	SUBNET=$(echo ${IP} | cut -d. -f 1-2)
	echo "Subnet: ${SUBNET}" >>/tmp/location_config.log
	DNSDOMAIN=$(debconf-get netcfg/get_domain)
	echo "DNS Domain: ${DNSDOMAIN}" >>/tmp/location_config.log

	MIRROR="archive.debian.org"
	if [ -n "${MIRROR}" ]; then
		echo "Local config selected, using mirror: ${MIRROR}" >>/tmp/location_config.log

		# do not ask questions about proxy
		db_fset mirror/protocol seen true
		db_fset mirror/http/proxy seen true

		db_set mirror/country "enter information manually"
		db_set mirror/http/countries "enter information manually"
		db_set mirror/http/hostname "${MIRROR}"
		db_set mirror/http/mirror "${MIRROR}"
		db_set apt-setup/hostname "${MIRROR}"
	fi
fi

