#!/bin/sh

# Parameters
export POSTINSTDIR=/var/lib/pf-fai
export POSTINST_LOG=/var/log/pf-fai/postinst.log


###########################################################################

echo "Bootstrapping FAI..."

mkdir -p $(dirname ${POSTINST_LOG})
echo "########################################################################" >>${POSTINST_LOG}
date >>${POSTINST_LOG}

COM="script -a -c ${POSTINSTDIR}/postinst_script ${POSTINST_LOG}"
if [ -f ${POSTINSTDIR}/debug ]; then
  ${COM}
else
  ${COM} >/dev/null 2>/dev/null
fi

