#!/bin/sh

# === Bootstrap ===

scr_print "Bootstrapping..."

# looking for the proper XIVO version
pkg_manager -y install pf-fai-xivo-0.1-arcadia
pkg_manager update

VERSION=$(apt-cache show --no-all-versions pf-xivo | grep Version | cut -d\  -f2)
if [ -z "${VERSION}" ]; then
	scr_println "XIVO not found"
	exit_error
fi

echo ${VERSION} >$POSTINSTDIR/xivo_initial_version

scr_progress_done


# === Install ===

scr_print "XIVO ${VERSION} installation in progress"

# inetd not needed
if [ -e /etc/init.d/inetd ]; then
	invoke-rc.d inetd stop
	update-rc.d -f inetd remove
fi

# XIVO install
pkg_manager -y install pf-xivo
scr_progress

scr_progress_done


# === Configuration ===

scr_println "XIVO configuration in progress..."

# Zaptel config
# (ignore errors caused by detection and config generation)
# (btw, the machine may not have any zaptel interface)
(
	# (restart to autoload modules)
	invoke-rc.d zaptel restart
	genzaptelconf -c fr
	# fix rights
	CONFIG="/etc/asterisk/zapata-channels.conf"
	if [ -e "${CONFIG}" ]; then
		chown asterisk:www-data ${CONFIG}
		chmod 660 ${CONFIG}
	fi
	# (restart with new config)
	invoke-rc.d zaptel restart
) >/dev/null 2>/dev/null || true

# Asterisk proper start
invoke-rc.d asterisk restart

scr_progress_done

