#!/bin/sh

scr_print "Bootcamp installation in progress"

# inetd not needed
if [ -e /etc/init.d/inetd ]; then
	invoke-rc.d inetd stop
	update-rc.d -f inetd remove
fi

# additionnal packages
pkg_manager -y install gcc libstdc++5 libncurses5-dev linux-headers-2.6.18-4-686 libnewt-dev libssl-dev libmysqlclient15-dev
scr_progress

# special user with sudo
useradd -m -g users -c "Bootcamp" -p '$1$FHWtzU/P$sEIR3FesRK1Dk6Dkzy/Px.' eleve
echo -e "eleve\tALL=(ALL) ALL" >>/etc/sudoers
scr_progress

# needed sources
wget -O /tmp/sources.tgz ftp://fai.proformatique.com/fai/bootcamp/bootcamp_install.tgz
cd /usr/src
tar xvzf /tmp/sources.tgz
rm /tmp/sources.tgz
cd -
scr_progress

# xorg config
wget -O /etc/X11/xorg.conf ftp://fai.proformatique.com/fai/bootcamp/xorg.conf
scr_progress

scr_progress_done

