#!/bin/sh

scr_print "Desktop installation in progress"

# xorg config (borrowed from the bootcamp installation)
wget -O /etc/X11/xorg.conf ftp://fai.proformatique.com/fai/bootcamp/xorg.conf
scr_progress

scr_progress_done

