#!/bin/sh

echo 'XiOH configuration'
apt-get install -y rsync git-core > /dev/null
cd /tmp
git clone git://git.xivo.io/official/xioh/install.git --depth 1 xioh-install
rsync -av /tmp/xioh-install/etc/ /etc/
insserv xioh
rsync -av /tmp/xioh-install/modules/xioh /lib/modules/`uname -r`
rm /lib/modules/`uname -r`/kernel/drivers/net/e1000/e1000.ko
depmod -a
cp /tmp/xioh-install/thirdparty/IxPiuMicrocode.dat /lib/firmware/
mkdir /usr/share/doc/xioh
cp /tmp/xioh-install/README /usr/share/doc/xioh
# install IxPiuMicrocode data
mkdir /usr/share/doc/IxPiuMicrocode
cp /tmp/xioh-install/thirdparty/IxPiuMicrocode.license /usr/share/doc/IxPiuMicrocode
# fix grub2 defaults
sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT\).*/\1=""/' /etc/default/grub
sed -i 's/^\(GRUB_CMDLINE_LINUX\)=.*/\1="console=ttyS0,115200n8"/' /etc/default/grub
update-grub > /dev/null
# cleanup net rules
sed -i '/SUBSYSTEM/d' /etc/udev/rules.d/70-persistent-net.rules
echo "XiOH setup done, please read /usr/share/doc/xioh/README"
